services:
    Bugloos\ResponderBundle\Service\Paginator:
        public: true
        autowire: true
        arguments:
            $paginatorHandler: '@Bugloos\ResponderBundle\PaginatorHandler\Pagerfanta\PagerfantaHandler'
            $paginatorResponse: '@paginator_response'
            $defaultMaxItemsPerPage: '%default_max_items_per_page%'
            $defaultItemsPerPage: '%default_items_per_page%'
            $pageKeyInRequest: '%page_key_in_request%'
            $itemsPerPageKeyInRequest: '%items_per_page_key_in_request%'

    Bugloos\ResponderBundle\PaginatorHandler\Pagerfanta\PagerfantaHandler: ~
    
    Bugloos\ResponderBundle\Service\DefaultPaginatorResponse: ~
